export {default as Dashboard} from './Dashboard'
export {default as Statistic} from './Statistic'
export {default as ChatManagement} from './ChatManagement'
export {default as Settings} from './Settings'
export {default as Slide} from './Slide'